### ISSUE TITLE
Working directory  error..

### ISSUE THREAD

**Issue by huzaifah0x00** [sensepost/kwetza#10]
I run the tool using the defined syntax...
But when the apk decompiles it stores the decompiled app into apktool folder ...

**Comment by huzaifah0x00** [comment]
Into the apktool folder instead of current working directory

**Comment by huzaifah0x00** [comment]
YOU  should put "-o targetFolder" in the apktool command syntax.. i guess

**Comment by huzaifah0x00** [comment]
TargetFolder being the variable u defined in the program

**Comment by brompwnie** [comment]
Good day,
We are using the apktool defaults to keep the tool as simple as possible. It is a good idea to have the option to specify where to place the generated apk. Perhaps this could be implemented by someone and we can accept the pull request.
Thanks for your feedback and happy hacking!
