### ISSUE TITLE
Doesn't the tool suppose the app of chinese edtion?

### ISSUE THREAD

**Issue by Mkv4** [sensepost/kwetza#14]
Doesn't the tool suppose the app of chinese edtion?

**Comment by brompwnie** [comment]
Good day,
Could you please elaborate?

**Comment by Mkv4** [comment]
Thx bro, I've slove it, maybe some app cannot be decompile, sorry for my
poor English.  Have a good day, bro.

2017年6月11日星期日，Chris Le Roy <notifications@github.com> 写道：

**Comment by brompwnie** [comment]
Anytime bro!
