### ISSUE TITLE
use apksigner instead of jarsigner

### ISSUE THREAD

**Issue by anantshri** [sensepost/kwetza#16]
apksigner is recommended tool now. 
also note the change in order of zipalign and signing.
https://developer.android.com/studio/command-line/apksigner.html

**Comment by brompwnie** [comment]
Good day,
Thank you for your comment. Could you perhaps provide an example where apksigner is more beneficial when creating malicious Android applications?

**Comment by anantshri** [comment]
i don't see a major difference in current state. but apksigner is what google has started recommending for dev's so no idea if future might have specific features in it only. so you can may be treat it as a reminder that at one point in time you might have to move away from jarsigner and use apksigner.

**Comment by brompwnie** [comment]
Thanks for this. I've marked this as a feature enhancement.
