### ISSUE TITLE
AttributeError: 'module' object has no attribute '_base'

### ISSUE THREAD

**Issue by Bry-fi** [sensepost/kwetza#17]
Error when I ran on python 2.7.13

Traceback (most recent call last):
  File "kwetza.py", line 5, in <module>
    from bs4 import BeautifulSoup as Soup
  File "/usr/local/lib/python2.7/dist-packages/bs4/__init__.py", line 30, in <module>
    from .builder import builder_registry, ParserRejectedMarkup
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/__init__.py", line 314, in <module>
    from . import _html5lib
  File "/usr/local/lib/python2.7/dist-packages/bs4/builder/_html5lib.py", line 70, in <module>
    class TreeBuilderForHtml5lib(html5lib.treebuilders._base.TreeBuilder):
AttributeError: 'module' object has no attribute '_base'

**Comment by brompwnie** [comment]
Good day,
Could you please provide the command you executed that generated this? Also, this looks like an error generated from BeautifulSoup, a search on Google lead me to this link which may help, https://stackoverflow.com/questions/43023562/how-to-solve-module-object-has-no-attribute-base-issue.

**Comment by Bry-fi** [comment]
Sure. Anything running the application caused this error such as python kwetza.py -h or python kwetza.py hackme.apk 10.42.0.118 4444 yes

**Comment by brompwnie** [comment]
Hi there,
Does this error occur on other target APK's? It appears this may happen due to bSoup not  liking the decoded manifest. It may be specific to the APK or an issue with the bSoup instance on the host machine.
