### ISSUE TITLE
ERROR IN 'readPayloads' method

### ISSUE THREAD

**Issue by melisaraymond** [sensepost/kwetza#26]
ERROR IN 'readPayloads' method
[Errno 2] No such file or directory: '/root/kwetza/VideoPlayer/smali//gui/AssistActivity1.smali'

**Comment by brompwnie** [comment]
Hello,
Can you please provide all of the output from Kwetza?
Thank you

**Comment by melisaraymond** [comment]
I'm sorted

 

thanks

 

Sent: Sunday, October 22, 2017 at 2:32 AM
