### ISSUE TITLE
NO LAUNCHER FOUND, PLEASE SPECIFY A TARGET CLASS

### ISSUE THREAD

**Issue by HTerminal** [sensepost/kwetza#30]
The previous version was working fine with this apk but now i am having trouble, also i am not being able to backdoor instagam i know insta has a private api but still any suggestions. 

[+] APKTOOL DECOMPILED SUCCESS
[*] BYTING TCP COMMS
[*] ANALYZING ANDROID MANIFEST
[DEBUG] Attempting to find MAIN
[+] NO LAUNCHER FOUND, PLEASE SPECIFY A TARGET CLASS

**Comment by las12xc** [comment]
_                  _              ___    ___  
                                          | |                | |            |__ \  / _ \ 
 _ __ ___  _ __ ___  _ __ ___  _ __ ___   | | ____      _____| |_ ______ _     ) || | | |
| '_ ` _ \| '_ ` _ \| '_ ` _ \| '_ ` _ \  | |/ /\ \ /\ / / _ \ __|_  / _` |   / / | | | |
| | | | | | | | | | | | | | | | | | | | | |   <  \ V  V /  __/ |_ / / (_| |  / /_ | |_| |
|_| |_| |_|_| |_| |_|_| |_| |_|_| |_| |_| |_|\_\  \_/\_/ \___|\__/___\__,_| |____(_)___/ 

[*] DECOMPILING TARGET APK
[+] ENDPOINT IP:
[+] ENDPOINT PORT: 4444
[+] APKTOOL DECOMPILED SUCCESS
[*] BYTING TCP COMMS
[*] ANALYZING ANDROID MANIFEST
[DEBUG] Attempting to find MAIN
[+] NO LAUNCHER FOUND, PLEASE SPECIFY A TARGET CLASS
please fix replay to mee (:

**Comment by dckool** [comment]
i have same error

**Comment by dckool** [comment]
i have same error, if you fixed it, please tell me how did you do?

**Comment by HTerminal** [comment]
With insta apk this problem is constantly coming rest everything works file. They might be using something that doesn't let u decompile and recompile.
