### ISSUE TITLE
error 

### ISSUE THREAD

**Issue by theoneandonly-vector** [sensepost/kwetza#5]
[+] MMMMMMMM KWETZA
[*] DECOMPILING TARGET APK
!!!! ERROR IN 'initialize' method
list index out of range

**Comment by brompwnie** [comment]
This error from not providing the correct amount of arguments to kwetza.py. Please see the readme for command line usage.

**Comment by theoneandonly-vector** [comment]
Nope.. your'e wrong.

Am 25.11.2016 9:01 vorm. schrieb "Chris Le Roy" <notifications@github.com>:

**Comment by brompwnie** [comment]
Could you provide the command you executed and all the output?
