### ISSUE TITLE
 ERROR jarsigner: unable to open jar file

### ISSUE THREAD

**Issue by 0xIslamTaha** [sensepost/kwetza#6]
I would like to thank you for your helpful tool.

I followed your instructure and I enter the following command:
python ./kwetza.py telegram.apk 192.168.1.2 80 no

But, I got the following error cos of jassigner unable to open jar file
![screenshot from 2016-11-24 01-17-41](https://cloud.githubusercontent.com/assets/17981089/20599088/06d5b5d8-b255-11e6-9c35-f2e584ee9c49.png)

​
I will be pleasure if you can help to solve this error.

**Comment by brompwnie** [comment]
This error is indicating that "jarsigner" cannot find the APK in "telegram/dist". Confirm that there is an APK in "telegram/dist".
